📜Create texture atlas loading tutorial
KinsonDigital/VelaptorDocs pull request #27
Opened 2023-04-12 13:58 UTC by CalvinWilkinson

<h1 style="font-weight:bold" align="center">Documentation Change Pull Request</h1>
<h2 style="font-weight:bold" align="center">📋Review Checklist📋</h2>

- [ ] The **_head(source)_** branch for this pull request is a **_feature_** branch, with the correct naming syntax, in the following example:
  - A **_head(source)_** branch is the branch being merged into a target branch.
    <details closed><summary>Example</summary>

      ``` xml
      Syntax: feature/<issue-num>-<description>
      Example: feature/123-my-preview-feature
      ```
    </details>

- [ ] The **_head(source)_** branch for this pull request is created from a **_master_** branch.

- [ ] The **_base(target)_** branch for this pull request is a **_master_** branch.

- [ ] The associated issue exists and is linked to this pull request.
  - One issue per pull request.

- [ ] The pull request title matches the title of the associated issue.

- [ ] The labels attached to this PR match the labels attached to the associated issue.

- [ ] The project assigned matches the project of the associated issue.

- [ ] I have manually reviewed the newly added documentation changes for grammar and spelling issues to the best of my ability.

2023-04-14 07:55 UTC, KinsonDigitalAdmin approved these changes, later dismissed

2023-04-14 11:35 UTC, kselena requested changes

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/adding-content.mdx
> +learn how to add content to our game.
Reword
```suggestion
Content is the lifeblood of a game; without it, there is no game.  In this section, we will
learn how to add content to our game.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/adding-content.mdx
> +
Reword
```suggestion
Various types of content can be added to a game.  In this tutorial, we will be adding an image to our game which will be loaded and consumed by Velaptor and converted into a `Texture` object.  Other content such as fonts and sounds can also be added.  You can even build custom content loaders to load content types for your game.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/adding-content.mdx
> +The default kinds of content supported by Velaptor are:
Reword
```suggestion
The default content supported by Velaptor are:
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/adding-content.mdx
> +The only difference is the folder location you are adding your content to based on the type of content you are adding.
Reword
```suggestion
Below are the steps to add content to your game.  The steps are the same, no matter what kind of content you are adding; the only difference is the folder location.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
> +TODO: refer to adding content tutorial
Looks like this TODO can be completed.  Can you refer to the tutorial here?

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
>  Before we can render the font, we need to create the appropriate renderer to render what we want.
Reword
```suggestion
Now that we have loaded a font to be applied to the text we want to render, we can render the text.
However, before we can render the font, we need to create the appropriate renderer.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
> +any renderers and then invoke the `IRenderer.End()` when we are finished with all of our renderings.
Reword
```suggestion
After setting up a text renderer and selecting a font for rendering text, we can now render text on the screen using the font renderer. To achieve this, you can add the following code to the OnDraw() method. Remember to call IRenderer.Begin() before using any Render() methods for any renderers, and then call IRenderer.End() when you're done with all the renderings.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
>  Currently, Velaptor comes with 4 different default fonts.  All of the default fonts are _**Times New Roman**_.
Reword
```suggestion
Currently, four default fonts come _**built-into**_ Velaptor  and are _**Times New Roman**_.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
>  Default font types are the 4 types of fonts that come _**built-into**_ Velaptor. For more info, refer to the font guide.
Reword.  The first part of this sentence was combined with line 104. 
```suggestion
Default font types are the 4 types of fonts that come _**built-into**_ Velaptor. For more info, refer to the font guide.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
>  <!-- TODO: Need to create a link to the guide once it is created.-->
This TODO looks legit.  I didn't find a font guide, but I want to make sure.

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
> +Once we invoked the `End()` method, this is when the actual rendering occurs.
Reword.  Spelling. 

```suggestion
When we call any `Render()` method for any renderer types, we are adding textures to the _**'batch'**_.  Once we invoke the `End()` method, it tells Velaptor that we are done batching all of our textures and it renders them. 
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
> +2. Invoked all `Render()` methods for the current frame
Spelling
```suggestion
2. Invoke all `Render()` methods for the current frame
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
>  Some game engines and frameworks use the top left corner of an object when rendering at a particular position.  Velaptor does not work like this.
Grammar
```suggestion
Some game engines and frameworks use the top left corner of an object when rendering at a particular position.  Velaptor does not work like that.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
>  Now the best part!! Let's see the fruits of your labor and run the application.
Grammar
```suggestion
Now for the best part!! Let's see the fruits of your labor and run the application.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
> +A game cannot be a game without adding interactivity to make things happen.  Otherwise, you are just looking at a still picture!
Reword
```suggestion
A game isn't a game without adding interactivity, right?  
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
> +is rendering the screen.  Let's add something to give the application some life.
Grammar.  Add "to"
```suggestion
is rendering to the screen.  Let's add something to give the application some life.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/project-setup.mdx
> +This guide will show you the basics of creating a simple empty Velaptor application.
Grammar
```suggestion
This guide will show you the basics of creating a simple, empty Velaptor application.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/project-setup.mdx
> +automatically when minimized and to unpause when the window is maximized or restored.
Reword
```suggestion
This is a great location to run game logic that can do anything you need.  One good example is to pause your game
automatically when minimized and to unpause when the window is maximized or restored.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +If you are an experienced developer, you know what _**JSON**_ is.  But for the people
Gramamar.  Remove "But"
```suggestion
If you are an experienced developer, you know what _**JSON**_ is.  For the people
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +Though there is nothing wrong with rendering whole textures one at a time, there are some downsides and upsides.  In the end, it all depends on what you are trying to accomplish.
Reword
```suggestion
Though there is nothing wrong with rendering whole textures one at a time, there are pros and cons.  In the end, it all depends on what you are trying to accomplish.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +- **Reduces draw calls:** Reduces the number of times Velaptor needs to send data to the GPU and reduces the number of draw calls. This is because instead of sending data and making draw calls for ea
Reword
```suggestion
- **Reduces draw calls:** Reduces the number of times Velaptor needs to send data to the GPU and reduces the number of draw calls. Instead of sending data and making draw calls for each individual texture, you only have to for a single atlas texture.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +- **Easier management:** Easier to manage one large texture than many small ones, especially when it comes to loading and unloading textures and coordinating the draw calls between textures.  This re
Reword
```suggestion
- - **Easier management:** Easier to manage one large texture than many small ones, especially when it comes to loading and unloading textures and coordinating the draw calls between textures.  The result is less code.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +- **Smoother Animations:** Makes animations smoother by reducing the amount of time your game spends loading and unloading textures..
Remove extra . at the end
```suggestion
- **Smoother Animations:** Makes animations smoother by reducing the amount of time your game spends loading and unloading textures.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +It all depends on your goals.  All games do a mix between whole texture and atlas texture rendering.
Reword
```suggestion
It all depends on your goals.  All games use a combination of whole texture and atlas texture rendering.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +Various tools out there give you the ability to easily create atlas textures and meta-data.  An example of some tools that do this would be [Texture Packer](https://www.codeandweb.com/texturepacker)
Reword
```suggestion
There are various tools that give you the ability to easily create atlas textures and meta-data.  A couple examples are: [Texture Packer](https://www.codeandweb.com/texturepacker)
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +Do not overstress about whole vs atlas texture rendering.  This comes with practice and depends on your needs.
Grammar. Use a period after vs 
```suggestion
Do not overstress about whole vs. atlas texture rendering.  This comes with practice and depends on your needs.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +You can name the files whatever you want, but the file names exclude the extension must match.
Grammar
```suggestion
You can name the files whatever you want, but the file names, excluding the extensions, must match.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +_**$type**_: This is the type of the object.  This is used by the JSON serializer to know what type of object to create.
Reword
```suggestion
_**$type**_: This is the type of the object that is used by the JSON serializer to know what type of object to create.  
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +sub-texture, you would call `GetFrames("ship")` and you would only get an array with a single item.
Reword
```suggestion
_**Name**_: This is the name of the sub-texture and is what you will use in determining which group of frames animation you want to load and when calling the `GetFrames()` method.  If you wanted to load the meta-data for the _**ship**_
sub-texture, you would call `GetFrames("ship")` and you would only get an array with a single item.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +Think of a flip book.  If you were to flip through the pages of a flip book, you would see the animation.
Do people know what a flip book is anymore?  LOL!

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +animation as fast as the game would run, the animation be too fast.  We need to slow down the
Grammar
```suggestion
animation as fast as the game would run, the animation would move too fast.  We need to slow down the
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +as you want or as slow as you want.
Reword
```suggestion
How fast you want to run your animation is up to you.  You can make it run as fast or as slow as you want.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +animation to the desired speed so that it appears to be running smoothly.
Reword? Not exactly sure...
```suggestion
animation to the desired speed so that it runs smoothly.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +frames that will be rendered are frames 8 to 15.
Reword/grammar.  
```suggestion
The `startFrame` is the frame where the animation starts, which will be either 0 or 8.  If the flame has not grown to full size,
frames 0-7 will be used.  If the flame has grown to full size, frames 8-15 will be used.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +the higher the FPS.
Reword
```suggestion
FPS stands for frames per second, which, as the name implies, is the number of frames that are rendered per second.
The game loop consists of the two most important methods: `OnUpdate()` and `OnRender()`.
The `OnUpdate()` and `OnRender()` methods are called once per frame.  The speed (or frequency) at
which these methods are called is what determines the FPS of the game.  The faster the methods run,
the higher the FPS.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +To calculate the FPS, you would divide the number of frames rendered by the number of seconds that
Grammar
```suggestion
To calculate the FPS, divide the number of frames rendered by the number of seconds that
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +orientation the texture should be flipped.
Reword
```suggestion
Add two more class fields to the `Game` class.  The `random` field will be used to randomly choose between horizontal or non-horizontal orientation.  The `horizontalLayout` field will be the layout setting at the time of rendering.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +This is synonymous with flipping a coin.
Reword
```suggestion
Add the following code to randomly choose whether or not the flame should be flipped horizontally to the
bottom of the `if` block.  This will choose a number between the values 0 and 1. If 0 is chosen,
the flame will be flipped horizontally.  If 1 is chosen, the flame will not be flipped horizontally.

This is synonymous with flipping a coin.
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/intro.mdx
> +hours when all you want to do is create.  This is where Velaptor can help!!
Reword
```suggestion
Velaptor focuses on building your game instead of having to write low-level code. Rendering graphics,
keyboard and mouse input, sound, and other common effects required by games can take hours
(trust me, I know). This is where Velaptor can help!!
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/intro.mdx
> +Joining our GitHub community is a great opportunity. Our community is always eager to welcome
Grammar
```suggestion
Joining our GitHub community is a great opportunity to get to know us and our products. Our community is always eager to welcome
```

2023-04-14 11:35 UTC, kselena commented on docs/tutorials/intro.mdx
>  the links below for more info.
Reword
```suggestion
We work on this full-time and work hard to make Velaptor and all of the [KinsonDigital](https://github.com/KinsonDigital) projects as high quality, user-friendly and helpful as possible.  Any open-source developer will tell you that maintaining open-source projects are a ton of work.🥱  
If you are interested in contributing, refer to
the links below for more info.
```

2023-04-14 11:35 UTC, kselena commented on docusaurus.config.js
>    // metadata like html lang. For example, if your site is Chinese, you may want
Refactor meta-data (used in other places in this documentation) to metadata like you have below.  lang. should be spelled out. 
```suggestion
  // Even if you don't use internalization, you can use this field to set useful
  // metadata like html language. For example, if your site is Chinese, you may want
```

2023-04-15 10:36 UTC, KinsonDigitalAdmin requested changes
- [x] Move all of the into text words to the admonition titles
- [x] Replace all occurrences of "meta-data" with "metadata"
- [x] Update preview.18 and preview.19 docs
- [x] Replace all double spaces after a period that contains another sentence after with a single period

2023-04-15 10:52 UTC, CalvinWilkinson commented on docs/tutorials/guides/rendering-with-texture-atlas.mdx
> +Think of a flip book.  If you were to flip through the pages of a flip book, you would see the animation.
I created a link to a great video about flipbooks with millions of views.  😉

2023-04-15 11:18 UTC, kselena requested changes

2023-04-15 11:18 UTC, kselena commented on docs/tutorials/guides/hello-velaptor.mdx
> +A game isn't a game without behavior and the ability to interact to make things happen.  Otherwise, you are just looking at a still picture!
Reword
```suggestion
A game isn't a game without behavior and interaction; otherwise, you're looking at a still picture!
```

2023-04-15 12:05 UTC, kselena submitted a review, later dismissed

2023-04-15 12:14 UTC, kselena submitted a review, later dismissed

2023-04-15 12:29 UTC, kselena approved these changes

2023-04-15 13:07 UTC, KinsonDigitalAdmin approved these changes

2023-04-15 13:08 UTC, merged